include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "bin/cache/**"
    - "lib/i18n/messages_*.dart"
    - "lib/src/http/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - avoid_relative_lib_imports
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - cancel_subscriptions
    - close_sinks # not reliable enough
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_single_quotes
