name: in_app_calls_demo
description: Flutter in-app calls application example.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  agora_rtc_engine: 6.1.0
  bloc_concurrency: ^0.2.2
  cloud_firestore: ^4.7.1
  cloud_functions: ^4.3.1
  dio: ^5.1.2
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_callkit_voximplant: ^2.1.0
  flutter_voip_push_notification:
    git:
      url: https://github.com/peerwaya/flutter_voip_push_notification.git
  get_it: ^7.6.0
  injectable: ^2.1.2
  onesignal_flutter: ^3.2.8
  permission_handler: ^10.2.0

dev_dependencies:
  build_runner: ^2.4.5
  dart_code_metrics: ^5.7.3
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.6
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
