name: in_app_calls_demo
description: Flutter in-app calls application example.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_callkit_voximplant: ^2.1.0
  flutter_voip_push_notification:
    git:
      url: https://github.com/peerwaya/flutter_voip_push_notification.git
  onesignal_flutter: ^3.2.8
  permission_handler: ^10.2.0

dev_dependencies:
  dart_code_metrics: ^5.7.3
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
