name: in_app_calls_demo
description: Flutter in-app calls application example.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  agora_rtc_engine: 6.1.0
  bloc_concurrency: ^0.2.2
  cloud_firestore: ^4.7.1
  cloud_functions: ^4.3.1
  dio: ^5.1.2
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_callkit_voximplant: ^2.1.0
  flutter_keyboard_visibility: ^5.4.1
  flutter_svg: ^2.0.7
  flutter_voip_push_notification:
    git:
      url: https://github.com/peerwaya/flutter_voip_push_notification.git
  get_it: ^7.6.0
  injectable: ^2.1.2
  mask_text_input_formatter: ^2.4.0
  onesignal_flutter: ^3.2.8
  permission_handler: ^10.2.0

dev_dependencies:
  build_runner: ^2.4.5
  dart_code_metrics: ^5.7.3
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.6
  very_good_analysis: ^4.0.0

flutter_gen:
  integrations:
    flutter_svg: true

  fonts:
    outputs:
      class_name: AppFonts
  colors:
    outputs:
      class_name: AppColors
    inputs:
      - assets/colors/colors.xml

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Geometria
      fonts:
        - asset: assets/fonts/geometria/Geometria-Bold.ttf
          weight: 700
        - asset: assets/fonts/geometria/Geometria-Medium.ttf
          weight: 500
        - asset: assets/fonts/geometria/Geometria-Regular.ttf
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/proxima_nova/ProximaNova-Regular.ttf
          weight: 400
